### ISSUE TITLE
Does not work with new models (port 7676)

### ISSUE THREAD

**Issue by DanielRuf** [beejjacobs/node-samsung-remote#4]
New models do not have the 55000 port anymore. Do you know any working solution or a fix?

**Comment by goranefbl** [comment]
Did u manage to make it work with new port?

**Comment by DanielRuf** [comment]
@goranefbl we used the 1515 port

**Comment by goranefbl** [comment]
1515 does not work for me, i get device is unreachable, but 7676 seems working (series 5) except that when i run node test-with-device.js, it just go through each but does not affect TV at all, it does run "socket.on('connect'... but thats about it.

**Comment by DanielRuf** [comment]
@goranefbl Right. We use the business displays which has this port that you can enable through the settings (Samsung MDC/ Multiple Display Control) using FANET, setting a device ID and so on.

Take a look at the comments and especially the links at https://github.com/imbrianj/switchBoard/issues/55
