### ISSUE TITLE
How to authenticate remote?

### ISSUE THREAD

**Issue by christian-bromann** [beejjacobs/node-samsung-remote#5]
Hi,
first of all great work on this remote library 👏 

According to other remote libraries Samsung Smart TVs need to authenticate the remote App before it accepts any key commands. There is an [Java example](https://github.com/mhvis/samsung-tv-control/blob/master/src/main/java/nl/maartenvisscher/samsungtvcontrol/SamsungRemote.java#L139-L177) that shows how to do it. Probably older Smart TVs didn't require that or did you manage to disable that?

I will try to get this implemented. It will an async command that returns a promise and will be resolved once you authorise the remote app.

**Comment by christian-bromann** [comment]
Ok this is not relevant for me anymore as all 2016 models can be controlled over a rest API. Feel free to close.

**Comment by beejjacobs** [comment]
Hi,

Yeah I've still got an older model so haven't looked at the newer models. Glad you found what you need!
