### ISSUE TITLE
unable to import

### ISSUE THREAD

**Issue by kambojakhil1991** [beejjacobs/node-samsung-remote#6]
i am trying to acquire samaung remote

giving code let  ab= require(‘node-samsung-remote)

but not able to find even it is therr in node_modules package

dir 
proj-
       -node_modules
       -src-
             - op-
                     -js file having this import

**Comment by beejjacobs** [comment]
is this your code?
`let ab= require(‘node-samsung-remote)`

Make sure to include quotes around the name, you only have one at the start.
`let ab= require('node-samsung-remote')`

**Comment by kambojakhil1991** [comment]
i have done like this only but it is saying unable to find samaung remote in src folder
but package is under node_modules

**Comment by kambojakhil1991** [comment]
project 
_________node_modules
__________src
_____________....jsfiles have code to require samaung-remote

**Comment by beejjacobs** [comment]
Please can you post the error you get?

Did you run `npm install node-samsung-remote` (or `yarn install node-samsung-remote`)?

**Comment by kambojakhil1991** [comment]
Hi

I am able to fix this samsungremote import error
but now getting error in code samaung-remote.js. line 69 net.connect is not
found

even though node_modules contains net package

please help

regards
Akhil Kamboj

**Comment by beejjacobs** [comment]
Hi,

That is not an error from this project. Please refer to the project you're actually using [samsung-remote](https://github.com/natalan/samsung-remote).

Also note `net` is a built in module and should not appear in `node_modules`.
